HajosOldal.Web/Controllers/FelhasznalokController.cs
using AutoMapper;
using HajosOldal.Logic;
using HajosOldal.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HajosOldal.Repository;
using System.Data.Entity;

namespace HajosOldal.Web.Controllers
{
    public class FelhasznalokController : Controller
    {
        IFelhasznaloLogic logic;
        IMapper mapper;
        FelhasznaloViewModel vm;
        public FelhasznalokController()
        {
            HajosOldal.Data.DatabaseEntities  ctx = new HajosOldal.Data.DatabaseEntities();
            FelhasznaloRepository felgRepo = new FelhasznaloRepository(ctx);
            logic = new FelhasznaloLogic(felgRepo);
            mapper = MapperFactory.CreateMapper();

            vm = new FelhasznaloViewModel();
            vm.EditedFelhasznalo = new Felhasznalo();
            var felhasznalok = logic.Listazas();
            vm.ListOfFelhasznalok = mapper.Map < IQueryable<Data.Felhasznalo>, List<Models.Felhasznalo>>(felhasznalok);

        }

        private Felhasznalo GetFelhasznaloModel(int id)
        {
            Data.Felhasznalo oneFelasznalo = logic.GetOne(id);
            return mapper.Map<Data.Felhasznalo, Models.Felhasznalo>(oneFelasznalo);
        }
        // GET: Felhasznalok
        public ActionResult Index()
        {
            ViewData["editAction"] = "AddNew";
            return View("FelhasznaloIndex",vm);
        }

        // GET: Felhasznalok/Details/5
        public ActionResult Detail(int id)
        {
            return View("FelhasznalokAdatok",GetFelhasznaloModel(id));
        }

        public ActionResult Remove(int id)
        {
            TempData["editResult"] = "Delete FAIL";
            if (true)
            {
                logic.Torles(id);
                TempData["editResult"] = "Delete OK";
            }
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            ViewData["editAction"] = "Edit";
            vm.EditedFelhasznalo = GetFelhasznaloModel(id);
            return View("FelhasznaloEdit", vm.EditedFelhasznalo);
        }
        [HttpPost]
        public ActionResult Edit(Felhasznalo felhasznalo, string editAction)
        {
            if(ModelState.IsValid && felhasznalo != null)
            {
                TempData["editResult"] = "EditOK";
                if(editAction == "AddNew")
                {
                    Data.Felhasznalo felhUj = new Data.Felhasznalo();
                    felhUj.FelhasznaloID = felhasznalo.Id;
                    felhUj.Nev = felhasznalo.Nev;
                    felhUj.Email = felhasznalo.Email;
                    felhUj.Telefon = felhasznalo.Telefon;

                    logic.Hozzaadas(felhUj);
                }
                else
                {                    
                    logic.Nev_Modositas(felhasznalo.Id, felhasznalo.Nev);
                    logic.Email_Modositas(felhasznalo.Id, felhasznalo.Email);
                    logic.Telefon_Modositas(felhasznalo.Id, felhasznalo.Telefon);
                }
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ViewData["editAction"] = "Edit";
                vm.EditedFelhasznalo = felhasznalo;
                return View("FelhasznaloIndex", vm);
            }
        }
    }
}

HajosOldal.Web/Views/Felhasznalok/FelhasznaloEdit.cshtml
@model HajosOldal.Web.Models.Felhasznalo

<h2>Egy felhasználó szerkesztése</h2>

@using (Html.BeginForm("Edit", "Felhasznalok"))
{
    @Html.ValidationSummary()
    @Html.AntiForgeryToken()

    @Html.Hidden("editAction", ViewData["editAction"].ToString());

    <div class="editor-label">@Html.LabelFor(m => m.Id)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Id)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Nev)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Nev)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Telefon)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Telefon)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Email)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Email)</div>

    <input type="submit" value="SEND" />

}

HajosOldal.Web/Views/Felhasznalok/FelhasznaloIndex.cshtml
@model HajosOldal.Web.Models.FelhasznaloViewModel
@{
    ViewBag.Title = "FelhasznaloIndex";
}

<h2>FelhasznaloIndex</h2>

<p style="color:red; font-weight: bold">@TempData["editResult"]</p>

@Html.Partial("FelhasznaloEdit", Model.EditedFelhasznalo)

@Html.Partial("FelhasznaloList", Model.ListOfFelhasznalok)

HajosOldal.Web/Views/Felhasznalok/FelhasznaloList.cshtml
@model IEnumerable<HajosOldal.Web.Models.Felhasznalo>
<h2>A felhasználók listája</h2>

@if (Model.Count() == 0)
{
    <p>No data in the database</p>
}
else
{
<table border="1">
    <tr>
        <th>@Html.DisplayNameFor(m => m.First().Id)</th>
        <th>@Html.DisplayNameFor(m => m.First().Nev)</th>
        <th>Datasheet</th>
        <th>Delete</th>
        <th>Edit</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <th>@Html.DisplayFor(m => item.Id)</th>
            <th>@Html.DisplayFor(m => item.Nev)</th>
            <th>@Html.ActionLink("[SHOW]", "Detail", new { id = item.Id })</th>
            <th>@Html.ActionLink("[DEL]", "Remove", new { id = item.Id })</th>
            <th>@Html.ActionLink("[EDIT]", "Edit", new { id = item.Id })</th>
        </tr>
    }
</table>
}

HajosOldal.Web/Views/Felhasznalok/FelhasznalokAdatok.cshtml
@model HajosOldal.Web.Models.Felhasznalo
@{
    ViewBag.Title = "FelhasznalokAdatok";
}

<h2>Egy adott felhasználó</h2>

<a href="/Felhasznalok/Index">Vissza a listára.</a>
@Html.ActionLink("Vissza a listára", "Index");
<table>
    <tr>
        <td>A felhasználó ID-ja</td>
        <td>@Model.Id</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m=>m.Nev)</td>
        <td>@Html.DisplayFor(m=>m.Nev)</td>
    </tr>
</table>